# if you want to disable checkra1n patches DISABLE_CHECKRA1N_KERNEL_PATCHES = 1, 
# else DISABLE_CHECKRA1N_KERNEL_PATCHES 0
DISABLE_CHECKRA1N_KERNEL_PATCHES = 0

# Delay before calling vuln_kext_start!
ACTIVATION_DELAY = 120

TARGET_DIRECTORIES = kext_loader pongo_module vulnerable_kext

all: $(TARGET_DIRECTORIES)

.PHONY: all $(TARGET_DIRECTORIES)

export GLOBAL_DEFINES=-DDISABLE_CHECKRA1N_KERNEL_PATCHES=$(DISABLE_CHECKRA1N_KERNEL_PATCHES) -DKEXT_ACTIVATION_DELAY='$(ACTIVATION_DELAY)'

$(TARGET_DIRECTORIES):
	$(MAKE) -C $@

CLEAN_TARGET_DIRECTORIES = $(TARGET_DIRECTORIES:%=clean-%)

clean: $(CLEAN_TARGET_DIRECTORIES)

.PHONY: clean $(CLEAN_TARGET_DIRECTORIES)

$(CLEAN_TARGET_DIRECTORIES):
	$(MAKE) -C $(@:clean-%=%) clean
